version: 3

vars:
  QE_PATH: charts/query-exporter

tasks:
  test-query-exporter:
    cmds:
      - go test /...
  kube-linter:
    cmds:
      - kube-linter lint charts/query-exporter
  polaris:
    cmds:
      - polaris audit --helm-chart charts/query-exporter --only-show-failed-tests